Refactor psychrometric unit tests
cgsandford/improver pull request #3
Opened 2020-01-16 16:32 UTC by cgsandford

This is a tidy-up of the unit tests for `WetBulbTemperature`, as some duplication was introduced in the original PR.

Testing:
 - [x] Ran tests and they passed OK

2020-01-20 09:28 UTC, MoseleyS requested changes
This looks ok. I've just noticed that the AlmostEqual calls need the `decimal` keyword to make them appropriately strict.

2020-01-20 09:28 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_WetBulbTemperature.py
> +        expected = [6.06744631e-08, 1.31079322e-03, 1.77063149e-01]
Given the default behaviour of `assertArrayAlmostEqual` of `decimal=6`, I don't think the first value is being checked correctly. There also doesn't seem to be an appropriate setting for this whole array. Perhaps this one needs checking individually.

2020-01-20 09:28 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_WetBulbTemperature.py
>          self.assertArrayAlmostEqual(result, expected)
This needs `decimal=1`

2020-01-20 09:28 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_WetBulbTemperature.py
> +        self.assertArrayAlmostEqual(result.data, self.expected_wbt_data)
Needs `decimal=3`

2020-01-20 09:28 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_WetBulbTemperature.py
> +        self.assertArrayAlmostEqual(result.data, self.expected_wbt_data)
Needs `decimal=3`

2020-01-20 09:28 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_WetBulbTemperature.py
> +        self.assertArrayAlmostEqual(result.data, self.expected_wbt_data)
Needs `decimal=3`

2020-01-20 09:28 UTC, MoseleyS commented on improver_tests/psychrometric_calculations/test_WetBulbTemperature.py
> +        self.assertArrayAlmostEqual(result.data[1], self.expected_wbt_data)
Needs `decimal=3`

2020-01-20 10:51 UTC, MoseleyS approved these changes
In discussion, we decided to leave the `decimal=?` issue to a separate piece of work.

2020-01-24 10:38 UTC, neilCrosswaite approved these changes

2020-01-24 11:10 UTC, cgsandford commented
Rebased parent branch which was a mistake.  Have copied changed test file across to original PR and am closing this now.

2020-01-24 11:10 UTC, closed without merging